if(NOT DEFINED ENV{FT_CUDA_ROOT} OR "$ENV{FT_CUDA_ROOT}" STREQUAL "")
    message(FATAL_ERROR "Set FT_CUDA_ROOT to an explicit CUDA 12.x toolkit (12.9.x release candidate).")
endif()
if(NOT EXISTS "${CMAKE_CUDA_COMPILER}")
    message(FATAL_ERROR "CUDA compiler does not exist: ${CMAKE_CUDA_COMPILER}")
endif()
execute_process(COMMAND "${CMAKE_CUDA_COMPILER}" --version
    RESULT_VARIABLE ft_nvcc_result OUTPUT_VARIABLE ft_nvcc_version ERROR_VARIABLE ft_nvcc_error)
if(NOT ft_nvcc_result EQUAL 0 OR NOT ft_nvcc_version MATCHES "release 12\\.")
    message(FATAL_ERROR "P100 baseline requires CUDA 12.x. Compiler reported: ${ft_nvcc_version} ${ft_nvcc_error}")
endif()
if(NOT CMAKE_CUDA_ARCHITECTURES STREQUAL "60" OR GGML_CUDA_GRAPHS OR NOT GGML_CUDA)
    message(FATAL_ERROR "P100 baseline requires GGML_CUDA=ON, architecture 60, and CUDA graphs OFF.")
endif()
